### ISSUE TITLE
Provide a screenshot

### ISSUE THREAD

**Issue by faceleg** [billyvg/tigris.nvim#1]
Installed, but not sure if it's working. It'd be great if you could include a screenshot showing the expected behaviour?

**Comment by quozd** [comment]
I also can't see any difference. Not sure if everything was correctly installed.

**Comment by mkusher** [comment]
yeah, same problem. Also it's not clear from readme.md if the plugin runs automatically or I should manually run `:TigrisEnable`/`:TigresToggle`.

**Comment by billyvg** [comment]
It is very likely that it was not working when you tried it, oops. Please reinstall the plugin. 

@mkusher I have updated the README a bit, hopefully it's more clear now. You can start the plugin by `:TigrisStart` or configure `g:tigris#enabled` in your vimrc.

`:TigrisToggle` was broken before, so it should now work as expected.

Check out the debug section in the README if you are curious if it is working.

Edit: parsing on buffer enter doesn't seem to be working, so you'll have to run `:TigrisStart` for now

**Comment by mkusher** [comment]
@billyvg ~~after update I got this error on `:TigrisStar`: `unknown function _tigris_enable`
And on `:TigrisDebug`: `unknown function _tigris_highlight_debug`~~
Upd: https://github.com/billyvg/tigris.nvim/issues/3

**Comment by billyvg** [comment]
Added a screenshot with comparison
