### ISSUE TITLE
Errors on :TigrisStart and :TigrisDebug

### ISSUE THREAD

**Issue by mkusher** [billyvg/tigris.nvim#3]
After update I got this error on `:TigrisStar`: `unknown function _tigris_enable`
And on `:TigrisDebug`: `unknown function _tigris_highlight_debug`

**Comment by quozd** [comment]
Same here

```
1
Error detected while processing function tigris#enable:
line    4:
E117: Unknown function: _tigris_enable
```

Neovim 0.1.4, macOS 10.12beta

**Comment by billyvg** [comment]
Did you run `:UpdateRemotePlugins`?

**Comment by quozd** [comment]
@billyvg yes, sure.

**Comment by mkusher** [comment]
@billyvg yep, the problem was with not up-to-date remote plugins

**Comment by billyvg** [comment]
Just to be clear, is it working now after running `:UpdateRemotePlugins`?

**Comment by mkusher** [comment]
@billyvg looks like it is working now
