### ISSUE TITLE
Invalid argument: Channel doesn't exist

### ISSUE THREAD

**Issue by adambiggs** [billyvg/tigris.nvim#4]
After pulling down the latest changes, I get the following error whenever editing any `.js` files:

```
Error detected while processing TextChangedI Auto commands for "*.js":
E475: Invalid argument: Channel doesn't exist
```

**Comment by billyvg** [comment]
Hmm this probably means an uncaught exception in the plugin caused the node client to crash. Unfortunately, I think the only way to fix this is to restart nvim (You could try `:UpdateRemotePlugins` first). If you set the environment variable `NEOVIM_JS_DEBUG` to a filename, the plugin will log to that file - that would help me understand a bit what happened.
