### ISSUE TITLE
E117: Unknown function: tigris enable

### ISSUE THREAD

**Issue by alistaircolling** [billyvg/tigris.nvim#7]
Hi, I can't seem to get the highlighting working with tigris, I've installed via vim-plug and ran `PlugInstall` which triggered the npm installs. I then ran `install.sh` from `tigris.vim`. 

I've added to my init.vim:
`let g:tigris#enabled = 1`

The highlighting isn't working. When I run `TigrisStart` I get this message:
`E117: Unknown function: tigris enable`

When I run `TigrisToggle` I get this message:
`E117: Unknown function: tigris toggle`

When I run `TigrisDebug` I get this message:
`E117: Unknown function: tigris highlight debug`

Can you help?! 
Thanks :)

**Comment by billyvg** [comment]
Do you have `node-host` installed and did you run `:UpdateRemotePlugins`?
do you see `tigris` listed after running `:UpdateRemotePlugins`?

**Comment by alistaircolling** [comment]
Hey @billyvg thanks for the quick response :) 
It was because I hadn't run `:UpdateRemotePlugins`
I can run tirgis now but I don't see the highlighting - when running in debug mode I get the message:
`Error: position does not exist`
Can you help with this - or should I start a new issue?

Thanks!
Alistair
